{ lib, pkgs, craneLibNative, craneLibWasm, pyroductDep }:

let
  # Helper to convert a Nix attrset to TOML
  toToml = import ./to-toml.nix { inherit lib; };

  # --- Shared Helper: mkDep ---
mkDep = { name, optional ? false, features ? [], ... }@args:
    let
      base = builtins.removeAttrs args [ "name" "optional" "features" ];

      # 2. Add back optional/features if needed
      withOptional = if optional then base // { optional = true; } else base;
      withFeatures = if features != [] then withOptional // { inherit features; } else withOptional;
    in 
      # 3. Optimization: If the only key is 'version', just return the string "1.2.3"
      #    Otherwise, return the full table { version = "..."; features = [...]; }
      if (builtins.attrNames withFeatures == [ "version" ]) then withFeatures.version
      else withFeatures;

  # --- 1. Import the TOML Generators ---
  makeCapabilityToml = import ./toml_capability.nix {
    inherit lib toToml mkDep pyroductDep;
  };
  
  makeModuleToml = import ./toml_module.nix {
    inherit lib toToml mkDep pyroductDep;
  };

  # --- 2. Import the Builders ---
  buildCapabilityImpl = import ./build_capability.nix {
    inherit pkgs lib craneLibNative makeCapabilityToml;
  };

  buildModuleImpl = import ./build_module.nix {
    inherit pkgs lib craneLibWasm makeModuleToml;
  };

  # --- Generator Script Logic ---
  generatedHeader = ''
# ============================================================================
# AUTO-GENERATED BY NIX
# ============================================================================
# This file points to dependencies in the /nix/store.
# If you edit a dependency, you must rebuild the flake for this file to update.
'';
  withHeader = content: generatedHeader + content;

  mkGenerateCargoTomlScript = items: pkgs.writeShellScriptBin "generate-cargo-toml" ''
    set -euo pipefail
    
    echo "Generating Cargo.toml files..."
    
    ${lib.concatMapStringsSep "\n" (item: ''
      echo "  Writing ${item.path}/Cargo.toml"
      mkdir -p "${item.path}"
      cat > "${item.path}/Cargo.toml" << 'CARGO_TOML_EOF'
${withHeader item.content}
CARGO_TOML_EOF
    '') items}
    
    echo "Done. Generated ${toString (lib.length items)} Cargo.toml files."
  '';

  collectGenerationTargets = { capabilities ? {}, modules ? {} }:
    (lib.concatMap (cap: 
       if (cap ? srcPath && cap.srcPath != null) then [{
         path = cap.srcPath;
         content = cap.cargoTomlContent;
       }] else []
    ) (lib.attrValues capabilities))
    ++
    (lib.mapAttrsToList (name: mod: {
      path = mod.srcPath;
      content = mod.cargoTomlContent;
    }) modules);

in {
  buildCapability = buildCapabilityImpl;
  buildModule = buildModuleImpl;
  inherit toToml mkDep mkGenerateCargoTomlScript collectGenerationTargets;
}