{ lib, pkgs, craneLibNative, craneLibWasm, workspaceRoot, pyroduct }:

let
  # Helper to convert a Nix attrset to TOML
  toToml = import ./to-toml.nix { inherit lib; };

  # --- Shared Helper: mkDep ---
  mkDep = { name, version ? null, path ? null, optional ? false, features ? [], ... }:
    let
      base = {}
        // (if path != null then { inherit path; } else {})
        // (if version != null then { inherit version; } else {});
      withOptional = if optional then base // { optional = true; } else base;
      withFeatures = if features != [] then withOptional // { inherit features; } else withOptional;
    in 
      if withFeatures == { version = version; } then version
      else withFeatures;

  # --- Import the separated Builders ---
  buildCapabilityImpl = import ./build_capability.nix {
    inherit pkgs lib craneLibNative toToml mkDep;
  };

  buildModuleImpl = import ./build_module.nix {
    inherit pkgs lib craneLibWasm toToml mkDep;
  };

  # --- Generator Script Logic ---
  generatedHeader = ''
# ============================================================================
# AUTO-GENERATED BY NIX
# ============================================================================
# This file points to dependencies in the /nix/store.
# If you edit a dependency, you must rebuild the flake for this file to update.
'';

  withHeader = content: generatedHeader + content;

  mkGenerateCargoTomlScript = items: pkgs.writeShellScriptBin "generate-cargo-toml" ''
    set -euo pipefail
    
    echo "Generating Cargo.toml files..."
    
    ${lib.concatMapStringsSep "\n" (item: ''
      echo "  Writing ${item.path}/Cargo.toml"
      mkdir -p "${item.path}"
      cat > "${item.path}/Cargo.toml" << 'CARGO_TOML_EOF'
${withHeader item.content}
CARGO_TOML_EOF
    '') items}
    
    echo "Done. Generated ${toString (lib.length items)} Cargo.toml files."
  '';

  collectGenerationTargets = { capabilities ? {}, modules ? {} }:
    (lib.concatMap (cap: 
       if (cap ? srcPath && cap.srcPath != null) then [{
         path = cap.srcPath;
         content = cap.cargoTomlContent;
       }] else []
    ) (lib.attrValues capabilities))
    ++
    (lib.mapAttrsToList (name: mod: {
      path = mod.srcPath;
      content = mod.cargoTomlContent;
    }) modules);

in {
  buildCapability = buildCapabilityImpl;
  buildModule = buildModuleImpl;
  inherit toToml mkDep mkGenerateCargoTomlScript collectGenerationTargets;
}