[capability]
authors = ["nbhdai"]
version = "0.1.0"
name = "rag"

[pyroduct]
path = "../../lib/pyroduct"  

[dependencies.host]
reqwest = { version = "0.13.1", features = ["json"] }
  
[dependencies.module]

[dependencies.shared]
