[package]
name = "pyroduct-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
module-core.workspace = true
capability-core.workspace = true
pyroduct.workspace = true
wasmtime.workspace = true
arrow-file.workspace = true

clap.workspace = true
fs-err.workspace = true
flate2.workspace = true
tar.workspace = true
heck.workspace = true

cargo_toml.workspace = true
toml.workspace = true
serde_json.workspace = true
serde.workspace = true
anyhow.workspace = true

tokio.workspace = true

syn.workspace = true
prettyplease.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true
wasmprinter = "0.244.0"
object = { version = "0.38.1", features = ["macho"] }
