#![doc = r" Automatically generated by pyroduct. DO NOT EDIT."]
#![allow(unused_imports, dead_code, unused_variables)]
use pyroduct;
#[derive(
    :: pyroduct :: rkyv :: Archive,
    :: pyroduct :: rkyv :: Serialize,
    :: pyroduct :: rkyv :: Deserialize,
)]
# [rkyv (crate = :: pyroduct :: rkyv)]
pub struct SerialClient {
    pub port_path: String,
}
impl SerialClient {
    pub fn register(self) -> Result<::pyroduct::module_capability::Client<Self>, String> {
        let __config_buf = ::pyroduct::rkyv::to_bytes::<::pyroduct::rkyv::rancor::Error>(&self)
            .expect("Failed to serialize config");
        let ffi_result =
            ::pyroduct::module_capability::access::call_from_wasm::<(), Result<(), String>, _>(
                "__serial_server__new_client",
                Some(&__config_buf),
                None,
                |client_state_ptr: *const u8,
                 client_state_len: usize,
                 input_ptr: *const u8,
                 input_len: usize| {
                    unsafe {
                        wasm::__serial_server__new_client__wasm(
                            client_state_ptr,
                            client_state_len,
                            input_ptr,
                            input_len,
                        )
                    }
                },
            );
        match ffi_result {
            Ok(_) => Ok(::pyroduct::module_capability::Client::new(
                self,
                __config_buf,
            )),
            Err(e) => Err(e.into()),
        }
    }
}
pub trait SerialClientMethods {
    fn open(&self) -> Result<(), String>;
    fn close(&self) -> Result<(), String>;
    fn write(&self, data: Vec<u8>) -> Result<usize, String>;
    fn read(&self, max_bytes: usize) -> Result<Vec<u8>, String>;
    fn write_line(&self, line: String) -> Result<usize, String>;
    fn read_line(&self) -> Result<String, String>;
    fn flush(&self) -> Result<(), String>;
}
impl SerialClientMethods for ::pyroduct::module_capability::Client<SerialClient> {
    #[doc = " Opens the serial port using tokio-serial's native async builder."]
    fn open(&self) -> Result<(), String> {
        ::pyroduct::module_capability::access::call_from_wasm::<(), Result<(), String>, _>(
            "__serial_server__open",
            Some(self.buffer()),
            None,
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__serial_server__open__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
    fn close(&self) -> Result<(), String> {
        ::pyroduct::module_capability::access::call_from_wasm::<(), Result<(), String>, _>(
            "__serial_server__close",
            Some(self.buffer()),
            None,
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__serial_server__close__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
    fn write(&self, data: Vec<u8>) -> Result<usize, String> {
        ::pyroduct::module_capability::access::call_from_wasm::<Vec<u8>, Result<usize, String>, _>(
            "__serial_server__write",
            Some(self.buffer()),
            Some(&data),
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__serial_server__write__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
    fn read(&self, max_bytes: usize) -> Result<Vec<u8>, String> {
        ::pyroduct::module_capability::access::call_from_wasm::<usize, Result<Vec<u8>, String>, _>(
            "__serial_server__read",
            Some(self.buffer()),
            Some(&max_bytes),
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__serial_server__read__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
    fn write_line(&self, line: String) -> Result<usize, String> {
        ::pyroduct::module_capability::access::call_from_wasm::<String, Result<usize, String>, _>(
            "__serial_server__write_line",
            Some(self.buffer()),
            Some(&line),
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__serial_server__write_line__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
    fn read_line(&self) -> Result<String, String> {
        ::pyroduct::module_capability::access::call_from_wasm::<(), Result<String, String>, _>(
            "__serial_server__read_line",
            Some(self.buffer()),
            None,
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__serial_server__read_line__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
    fn flush(&self) -> Result<(), String> {
        ::pyroduct::module_capability::access::call_from_wasm::<(), Result<(), String>, _>(
            "__serial_server__flush",
            Some(self.buffer()),
            None,
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__serial_server__flush__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
}
pub mod wasm {
    use super::*;
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "env")]
    unsafe extern "C" {
        pub fn __serial_server__new_client__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __serial_server__open__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __serial_server__close__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __serial_server__write__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __serial_server__read__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __serial_server__write_line__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __serial_server__read_line__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __serial_server__flush__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
    }
}
