//! This crate provides proc macros to generate FFI boilerplate for capabilities.
use syn::parse_file;

use crate::{
    ffi::{capability::CapabilityImpl, config::CapConfig},
    format::{
        bridgeable::{BridgeableArgs, DocRec},
        documentation::MagmaDocumentation,
        magma,
    },
};

pub mod capability;
pub mod config;
pub mod lifecycle;
pub mod methods;
pub mod paths;
pub mod spec;

/// For generating the interface lib.rs (module-side code)
pub fn generate_interface(
    content: &str,
    cap_name: &str,
    cap_version: &str,
) -> syn::Result<(
    syn::File,
    Result<String, serde_json::Error>,
    Option<Result<String, serde_json::Error>>,
)> {
    let file = parse_file(content)?;

    let failure_error = syn::Error::new_spanned(&file, "No capability found");

    let import_location: syn::Path = syn::parse_quote!(::pyroduct);

    // Build file-level schema registry (pass 1: collect all structs)
    let schema_builder = crate::struct_doc::SchemaBuilder::from_file(&file);

    let mut generated_code = quote::quote! {
        //! Automatically generated by pyroduct. DO NOT EDIT.
        #![allow(unused_imports, dead_code, unused_variables, nonstandard_style)]
        use pyroduct;
    };

    let mut capability = None;
    let mut interfaces = Vec::new();
    let mut config = None;
    for item in file.items {
        match item {
            syn::Item::Impl(item_impl) => {
                if has_attr(&item_impl.attrs, "capability") {
                    let cap = CapabilityImpl::new(item_impl, true, cap_name, cap_version)?;
                    generated_code.extend(cap.expand_module());
                    capability = Some(cap);
                }
            }
            syn::Item::Struct(mut item_struct) => {
                if let Some(args) = extract_magma_args(&item_struct.attrs)? {
                    // 2. Parse MagmaDocumentation before magma() mutates the struct
                    let documentation = MagmaDocumentation::from_item(&item_struct, DocRec::NoReq)?;

                    // 3. Strip the #[magma] attribute so magma() doesn't see it
                    item_struct.attrs.retain(|a| !is_magma_attr(a));

                    // 4. Expand via magma (import_location = pyroduct)
                    let expanded = magma(args, &mut item_struct, &import_location)?;
                    generated_code.extend(expanded);

                    // 5. Collect documentation for the spec
                    interfaces.push(documentation);
                } else if has_attr(&item_struct.attrs, "config") {
                    let found_config = CapConfig::new(item_struct, DocRec::StructDoc)?;
                    config = Some(found_config);
                }
            }
            _ => {}
        }
    }
    let mut spec_builder = if let Some(cap) = capability {
        spec::SpecBuilder::new(&cap, &schema_builder)
    } else {
        return Err(failure_error);
    };
    for interface in interfaces {
        spec_builder.append(&interface);
    }
    let spec = spec_builder.build();

    let config = if let Some(cap) = config {
        Some(spec::ConfigSpecBuilder::build(&cap, &schema_builder))
    } else {
        None
    };
    let code: syn::File = syn::parse2(generated_code)?;
    Ok((code, spec, config))
}

/// For generating the capability lib.rs (host-side code)
pub fn generate_capability(
    content: &str,
    cap_name: &str,
    cap_version: &str,
) -> syn::Result<syn::File> {
    let file = parse_file(content)?;

    let mut generated_code = quote::quote! {
        //! Automatically generated by pyroduct. DO NOT EDIT.
        #![allow(unused_imports, dead_code, unused_variables, nonstandard_style)]
        use ::pyroduct;
    };
    let import_location: syn::Path = syn::parse_quote!(::pyroduct);

    for item in file.items {
        match item {
            syn::Item::Impl(item_impl) => {
                if has_attr(&item_impl.attrs, "capability") {
                    let cap = CapabilityImpl::new(item_impl, true, cap_name, cap_version)?;
                    generated_code.extend(cap.expand_capability());
                }
            }
            syn::Item::Struct(mut item_struct) => {
                if let Some(args) = extract_magma_args(&item_struct.attrs)? {
                    let expanded = magma(args, &mut item_struct, &import_location)?;
                    generated_code.extend(expanded);
                } else if has_attr(&item_struct.attrs, "config") {
                    let found_config = CapConfig::new(item_struct, DocRec::StructDoc)?;
                    generated_code.extend(found_config.expand());
                }
            }
            _ => {}
        }
    }

    let code: syn::File = syn::parse2(generated_code)?;
    Ok(code)
}

/// Extract `BridgeableArgs` from a `#[magma(...)]` attribute.
/// Handles both `#[magma]` (no args) and `#[magma(derive(Debug))]`.
fn extract_magma_args(attrs: &[syn::Attribute]) -> syn::Result<Option<BridgeableArgs>> {
    for attr in attrs {
        if is_magma_attr(attr) {
            return match &attr.meta {
                syn::Meta::List(list) => {
                    syn::parse2::<BridgeableArgs>(list.tokens.clone()).map(Some)
                }
                syn::Meta::Path(_) => {
                    // Bare #[magma] with no arguments
                    Ok(Some(BridgeableArgs {
                        derives_to_pass: Vec::new(),
                        compares_to_add: Vec::new(),
                        doc_rec: DocRec::NoReq,
                    }))
                }
                syn::Meta::NameValue(nv) => Err(syn::Error::new_spanned(
                    nv,
                    "Invalid magma attribute format",
                )),
            };
        }
    }
    Ok(None)
}

fn is_magma_attr(attr: &syn::Attribute) -> bool {
    if attr.path().is_ident("magma") {
        return true;
    }
    if attr.path().segments.len() == 2
        && attr.path().segments[0].ident == "pyroduct"
        && attr.path().segments[1].ident == "magma"
    {
        return true;
    }
    false
}

fn has_attr(attrs: &[syn::Attribute], name: &str) -> bool {
    attrs.iter().any(|a| {
        if a.path().is_ident(name) {
            return true;
        }
        if a.path().segments.len() == 2
            && a.path().segments[0].ident == "pyroduct"
            && a.path().segments[1].ident == name
        {
            return true;
        }
        false
    })
}
