[package]
name = "capability-core"
version = "0.1.0"
authors = ["Sven Cattell"]
edition = "2024"

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
heck.workspace = true

# todo: remove this once we have a good user facing error struct
anyhow.workspace = true

# todo: remove these after moving "spec" into a seperate crate
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
prettyplease.workspace = true
