[package]
name = "pyro-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
serde_json.workspace = true

heck.workspace = true
prettyplease.workspace = true
serde.workspace = true

[dev-dependencies]
similar = "2.7"