capabilities:
  transform:
    path: ../../capabilities/config/
    classes:
      config:
        uppercase: true
        suffix: "!!!"

modules:
  prefix:
    path: ../../modules/cap_config/
    capabilities:
      - config

pipeline:
  - prefix