[workspace]
members = [ 
    "lib/harness",
    "lib/arrow-scalars",
    "lib/arrow-derive",
    "lib/capability-derive",
    "lib/module-derive",
    "lib/pyroduct", 

    "capabilities/rag",
    "capabilities/http_client",
    "capabilities/cpu_client",
    "capabilities/serial_client",

    "modules/basic",
    "modules/basic_capability",
    "modules/rag_capability",
    "modules/struct_io",
]

default-members = [
    "lib/harness",
    "lib/arrow-scalars",
    "lib/arrow-derive",
    "lib/capability-derive",
    "lib/module-derive",
    "lib/pyroduct", 

    # "capabilities/cpu_client", 
    # "capabilities/http_client", 
    # "capabilities/reporter", 
    # "capabilities/serial_client", 
    # 
    # "modules/basic",
    # "modules/basic_capability",
    # "modules/dual_capability",
    # "modules/state_capability",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Sven Cattell"]
edition = "2024"

[workspace.dependencies]
arrow-scalars = { path = "lib/arrow-scalars" }
pyroduct = { path = "lib/pyroduct" }