use std::path::{Path, PathBuf};
use std::io::Write;
use anyhow::{Context, Result};
use quote::quote;
use syn::parse_file;

// Import the parsing logic from your core crate
use capability_core::{capability::CapabilityImpl, config::CapConfig, client::CapClient};

mod cargo;

/// A builder for generating capability client code.
pub struct ClientGenerator {
    source_path: PathBuf,
    out_dir: PathBuf,
}

impl ClientGenerator {
    /// Create a new generator for a specific source file (e.g. "src/capability.rs")
    pub fn new(source_path: impl AsRef<Path>) -> Self {
        Self {
            source_path: source_path.as_ref().to_path_buf(),
            out_dir: std::env::var_os("OUT_DIR")
                .map(PathBuf::from)
                .unwrap_or_else(|| PathBuf::from(".")),
        }
    }

    /// Override the output directory (defaults to OUT_DIR)
    pub fn out_dir(mut self, out_dir: impl AsRef<Path>) -> Self {
        self.out_dir = out_dir.as_ref().to_path_buf();
        self
    }

    /// Reads the source file, extracts capabilities, and writes the generated client module.
    ///
    /// Returns the path to the generated file.
    pub fn generate(self, output_filename: &str) -> Result<PathBuf> {
        // 1. Re-run signal for Cargo
        println!("cargo:rerun-if-changed={}", self.source_path.display());

        // 2. Read and parse
        let content = std::fs::read_to_string(&self.source_path)
            .with_context(|| format!("Failed to read capability source: {:?}", self.source_path))?;
        
        let file = parse_file(&content)
            .context("Failed to parse capability source file")?;

        // 3. Header for the generated file
        let mut generated_code = quote! {
            //! Automatically generated by capability-module. DO NOT EDIT.
            #![allow(unused_imports, dead_code, unused_variables)]
            use pyroduct;
        };

        // 4. Iterate over items and expand
        for item in file.items {
            match item {
                // Handle impl blocks: #[capability]
                syn::Item::Impl(item_impl) => {
                    if has_attr(&item_impl.attrs, "capability") {
                        let cap = CapabilityImpl::new(item_impl)
                             .map_err(|e| anyhow::anyhow!("{}", e))?;
                        
                        // Assumes capability-core has this method exposed
                        generated_code.extend(cap.expand_module()); 
                    }
                }
                
                // Handle structs: #[config] or #[client]
                syn::Item::Struct(item_struct) => {
                    if has_attr(&item_struct.attrs, "config") {
                        let config = CapConfig::new(item_struct)
                             .map_err(|e| anyhow::anyhow!("{}", e))?;
                        generated_code.extend(config.expand());
                    } else if has_attr(&item_struct.attrs, "client") {
                        let client = CapClient::new(item_struct)
                             .map_err(|e| anyhow::anyhow!("{}", e))?;
                        generated_code.extend(client.expand());
                    }
                }
                _ => {}
            }
        }

        // 5. Write output
        let dest_path = self.out_dir.join(output_filename);
        let mut out_file = std::fs::File::create(&dest_path)
            .with_context(|| format!("Failed to create output file: {:?}", dest_path))?;
        
        out_file.write_all(generated_code.to_string().as_bytes())?;

        Ok(dest_path)
    }
}

/// Helper to check for attributes like #[capability] or #[pyroduct::capability]
fn has_attr(attrs: &[syn::Attribute], name: &str) -> bool {
    attrs.iter().any(|a| {
        if a.path().is_ident(name) {
            return true;
        }
        if a.path().segments.len() == 2 
           && a.path().segments[0].ident == "pyroduct" 
           && a.path().segments[1].ident == name {
            return true;
        }
        false
    })
}