#![doc = r" Automatically generated by pyroduct. DO NOT EDIT."]
#![allow(unused_imports, dead_code, unused_variables, nonstandard_style)]
use pyroduct;
#[derive(
    :: pyroduct :: rkyv :: Archive,
    :: pyroduct :: rkyv :: Serialize,
    :: pyroduct :: rkyv :: Deserialize,
)]
# [rkyv (crate = :: pyroduct :: rkyv)]
#[doc = " The Pyroduct interface item representing the HTTP Client."]
pub struct HttpClient;
impl HttpClient {
    pub fn register(self) -> Result<::pyroduct::module_capability::Client<Self>, String> {
        let __config_buf = ::pyroduct::rkyv::to_bytes::<::pyroduct::rkyv::rancor::Error>(&self)
            .expect("Failed to serialize config");
        let ffi_result =
            ::pyroduct::module_capability::access::call_from_wasm::<(), Result<(), String>, _>(
                "__http_server__new_client",
                Some(&__config_buf),
                None,
                |client_state_ptr: *const u8,
                 client_state_len: usize,
                 input_ptr: *const u8,
                 input_len: usize| {
                    unsafe {
                        wasm::__http_server__new_client__wasm(
                            client_state_ptr,
                            client_state_len,
                            input_ptr,
                            input_len,
                        )
                    }
                },
            );
        match ffi_result {
            Ok(_) => Ok(::pyroduct::module_capability::Client::new(
                self,
                __config_buf,
            )),
            Err(e) => Err(e.into()),
        }
    }
}
pub trait HttpClientMethods {
    #[doc = " Performs an asynchronous GET request if the URL and method are allowed."]
    fn get(&self, url: String) -> Result<String, String>;
    #[doc = " Performs an asynchronous POST request with a body if the URL and method are allowed."]
    fn post(&self, url: String, body: String) -> Result<String, String>;
    #[doc = " Performs an asynchronous PUT request with a body if the URL and method are allowed."]
    fn put(&self, url: String, body: String) -> Result<String, String>;
    #[doc = " Performs an asynchronous DELETE request if the URL and method are allowed."]
    fn delete(&self, url: String) -> Result<String, String>;
}
impl HttpClientMethods for ::pyroduct::module_capability::Client<HttpClient> {
    #[doc = " Performs an asynchronous GET request if the URL and method are allowed."]
    fn get(&self, url: String) -> Result<String, String> {
        ::pyroduct::module_capability::access::call_from_wasm::<String, Result<String, String>, _>(
            "__http_server__get",
            Some(self.buffer()),
            Some(&url),
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__http_server__get__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
    #[doc = " Performs an asynchronous POST request with a body if the URL and method are allowed."]
    fn post(&self, url: String, body: String) -> Result<String, String> {
        #[derive(
            :: pyroduct :: rkyv :: Archive,
            :: pyroduct :: rkyv :: Deserialize,
            :: pyroduct :: rkyv :: Serialize,
        )]
        # [rkyv (crate = :: pyroduct :: rkyv)]
        struct __HttpServer__Post__Input {
            pub url: String,
            pub body: String,
        }
        ::pyroduct::module_capability::access::call_from_wasm::<
            __HttpServer__Post__Input,
            Result<String, String>,
            _,
        >(
            "__http_server__post",
            Some(self.buffer()),
            Some(&__HttpServer__Post__Input { url, body }),
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__http_server__post__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
    #[doc = " Performs an asynchronous PUT request with a body if the URL and method are allowed."]
    fn put(&self, url: String, body: String) -> Result<String, String> {
        #[derive(
            :: pyroduct :: rkyv :: Archive,
            :: pyroduct :: rkyv :: Deserialize,
            :: pyroduct :: rkyv :: Serialize,
        )]
        # [rkyv (crate = :: pyroduct :: rkyv)]
        struct __HttpServer__Put__Input {
            pub url: String,
            pub body: String,
        }
        ::pyroduct::module_capability::access::call_from_wasm::<
            __HttpServer__Put__Input,
            Result<String, String>,
            _,
        >(
            "__http_server__put",
            Some(self.buffer()),
            Some(&__HttpServer__Put__Input { url, body }),
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__http_server__put__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
    #[doc = " Performs an asynchronous DELETE request if the URL and method are allowed."]
    fn delete(&self, url: String) -> Result<String, String> {
        ::pyroduct::module_capability::access::call_from_wasm::<String, Result<String, String>, _>(
            "__http_server__delete",
            Some(self.buffer()),
            Some(&url),
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__http_server__delete__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
}
mod wasm {
    use super::*;
    #[link(wasm_import_module = "env")]
    unsafe extern "C" {
        pub fn __http_server__new_client__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __http_server__get__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __http_server__post__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __http_server__put__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __http_server__delete__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
    }
}
