[package]
name = "rag_capability"
version = "0.1.0"
edition = "2024"
authors = ["nbhdai"]

[dependencies]
text-splitter = "0.15"

[dependencies.getrandom]
version = "0.3"
features = ["wasm_js"]

[dependencies.pyroduct]
path = "../../lib/pyroduct"

[dependencies.rag]
path = "../../capabilities/rag/interface"

[target.wasm32-unknown-unknown.dependencies]

[target.wasm32-unknown-unknown.dev-dependencies]

[target.wasm32-unknown-unknown.build-dependencies]

[lib]
crate-type = ["cdylib"]
required-features = []
