[package]
name = "rag_capability"
version = "0.1.0"
edition = "2024"
authors = ["nbhdai"]

[workspace]
members = []

[dependencies]
text-splitter = "0.15"

[dependencies.pyroduct]
path = "../../lib/pyroduct"

[dependencies.rag]
path = "../../capabilities/rag/module"
optional = true

[lib]
crate-type = ["cdylib"]
required-features = []
