[package]
name = "bridge-vec"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bridge-derive.workspace = true
rkyv.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
trybuild.workspace = true
macrotest = "1.0"
