[module]
author = "nbhdai"
name = "rag_capability"
version = "0.1.0"

[pyroduct]
version = "0.1.0"

[capabilities]
rag = { package = "rag", author = "nbhdai", version = "0.1.0" }

[dependencies]
text-splitter = "0.15"
# This is to clean up a wasm problem
getrandom = { version = "0.3", features = ["wasm_js"] }

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']