[module]
author = "nbhdai"
package = "rag_capability"
version = "0.1.0"

[pyroduct]
path = "../../lib/pyroduct/"

[capabilities]
rag = { package = "rag", author = "nbhdai", version = "0.1.0", configuration = { type = "capabilityconfig", classes = { ragserver = { top_k = 3, documents = [ { id = "doc1", content = "Pyroduct is a high-performance Python-like WebAssembly runtime." }, { id = "doc2", content = "Capabilities in Pyroduct are compiled as native shared libraries." } ] } } } }

[dependencies]
text-splitter = "0.15"
# This is to clean up a wasm problem
getrandom = { version = "0.3", features = ["wasm_js"] }

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']