use pyro_vec::{
    captured::{CapturedError, LibraryInfo},
    library,
};

library!("pyroduct-meta-v1");

#[test]
fn test_library_identity() {
    // Verify the generated constants match the package info
    assert_eq!(Library::META, "pyroduct-meta-v1");
}

#[test]
fn test_captured_error_includes_library_ident() {
    Library::register_info();
    // 2. Create a new captured error
    // The constructor calls APP_IDENTITY.get() internally
    let error = CapturedError::new("Something went sideways");

    // 3. Verify the library info is present
    let lib_info = error
        .library
        .as_ref()
        .expect("Library info should be captured");
    println!("{lib_info:?}");

    // Check that the metadata we passed to the macro is there
    assert_eq!(lib_info.meta, "pyroduct-meta-v1");

    // Check that Cargo environment variables were correctly pulled
    // These will match the [package] section of your pyro_vec or test crate
    assert_eq!(lib_info.name, env!("CARGO_PKG_NAME"));
    assert_eq!(lib_info.version, env!("CARGO_PKG_VERSION"));

    // 4. Verify Display implementation includes the message
    let display_msg = format!("{}", error);
    assert!(display_msg.contains("Something went sideways"));
}

#[test]
fn test_error_serialization_preserves_library_info() {
    Library::register_info();
    let error = CapturedError::new("Persistence failure");

    // Serialize to JSON (as used in pyro_vec internal encoding)
    let serialized = serde_json::to_string_pretty(&error).expect("Should serialize to JSON");
    println!("{serialized}");
    // Ensure the library identity is present in the serialized output
    assert!(serialized.contains("pyroduct-meta-v1"));
    assert!(serialized.contains(env!("CARGO_PKG_NAME")));
}

#[test]
fn test_ffi_exposure_consistency() {
    // 1. Register info to ensure we have a baseline to compare against
    let rust_info = Library::register_info();

    // 2. Retrieve data via the generated C-ABI functions
    // These functions are generated by the library! macro at the top of the file
    let ffi_ptr = library_json_ptr();
    let ffi_len = library_json_len();

    assert!(!ffi_ptr.is_null(), "FFI pointer should not be null");
    assert!(ffi_len > 0, "FFI length should be greater than zero");

    // 3. Reconstruct the JSON string from raw parts
    let ffi_slice = unsafe { std::slice::from_raw_parts(ffi_ptr, ffi_len) };
    let ffi_str = std::str::from_utf8(ffi_slice).expect("FFI data must be valid UTF-8");

    println!("FFI Exposed JSON: {}", ffi_str);

    // 4. Deserialize the FFI string back into LibraryInfo
    let ffi_info: LibraryInfo =
        serde_json::from_str(ffi_str).expect("FFI JSON must match the LibraryInfo schema");

    // 5. Verify exact equality between Rust-registered info and FFI-exposed info
    assert_eq!(ffi_info.meta, rust_info.meta);
    assert_eq!(ffi_info.name, rust_info.name);
    assert_eq!(ffi_info.version, rust_info.version);

    // 6. Double check specific values to ensure they match expected environment
    assert_eq!(ffi_info.meta, "pyroduct-meta-v1");
    assert_eq!(ffi_info.name, env!("CARGO_PKG_NAME"));
}
