[package]
name = "cache"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
cargo_toml.workspace = true
flate2.workspace = true
pyro-core.workspace = true
pyroduct.workspace = true
serde.workspace = true
sha2.workspace = true
tar.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
