[workspace]
members = [ 
    "harness",
    "arrow-scalars",
    "arrow-derive",
    "capability-core",
    "capability-derive",
    "module-derive",
    "pyroduct", 
]

default-members = [
    # "lib/harness",
    "lib/arrow-scalars",
    "lib/arrow-derive",
    "lib/capability-derive",
    "lib/module-derive",
    "lib/pyroduct",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Sven Cattell"]
edition = "2024"

[workspace.dependencies]
arrow-scalars = { path = "lib/arrow-scalars" }
pyroduct = { path = "lib/pyroduct" }