[workspace]
members = [ 
    "pyroduct",
    "pyro-macro",
    "pyro-derive",
    "pyro-file",
    "pyro-spec",
    "pyro-artifacts",
    "pyro-daemon",
    "pyro-gui",
]

default-members = [
    "pyroduct",
    "pyro-macro",
    "pyro-file",
    "pyro-spec",
    "pyro-artifacts",
    "pyro-daemon",
    "pyro-gui",
]
resolver = "2"

[workspace.package]
version = "0.2.6"
authors = ["nbhd ai"]
license = "AGPL-3.0"
keywords = ["wasm", "machine-learning"]
repository = "https://github.com/nbhdai/pyroduct"
edition = "2024"
rust-version = "1.90"
homepage = "https://nbhd.ai"


[workspace.dependencies]
pyro-macro = { path = "pyro-macro", version = "0.2.6" }
pyro-derive = { path = "pyro-derive", version = "0.2.6" }
pyroduct = { path = "pyroduct", version = "0.2.6" }
pyro-file = { path = "pyro-file", version = "0.2.6" }
pyro-spec = { path = "pyro-spec", version = "0.2.6" }
pyro-artifacts = { path = "pyro-artifacts", version = "0.2.6" }
pyro-daemon = { path = "pyro-daemon", version = "0.2.6" }
pyro-gui = { path = "pyro-gui", version = "0.2.6" }

# Errors and reporting
anyhow = "1.0.100"
thiserror = "2.0.17"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
tracing-test = "0.2.5"
rusqlite = { version = "0.32.1", features = ["bundled"] }

# Serialization
rkyv = "0.8.14"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_yaml = "0.9.34"
toml = "0.9.11"
half = { version = "2.7.1", features = ["serde", "rkyv"] }

# Arrow 
arrow = "57.2.0"
parquet = "57.2.0"
arrow-schema = "57.2.0"
datafusion = "51"


# I/O and hashing
bytes = "1.11.0"
memmap2 = "0.9.9"
sha2 = "0.10.9"
semver = "1"
rand = "0.9"
tempfile = "3.24.0"
fs-err = "2.9"
tar = "0.4.44"
flate2 = "1.1.8"
# ClI and TUI
clap = { version = "4.5", features = ["derive"] }

# Async and ffi
wasmtime = "41.0.3"
pin-project = "1.1.10"
tokio = { version = "1.49.0", features = ["full"] }
futures = "0.3.31"
async-ffi = "0.5.0"
object = { version = "0.38.1", features = ["macho"] }
libloading = "0.9.0"
axum = "0.7.9"

# Macro & Expansion
cargo_toml = "0.22.3"
proc-macro2 = { version ="1.0",  features = ["span-locations"] }
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits", "parsing"] }
heck = "0.5.0"
prettyplease = "0.2.37"
trybuild = "1.0"
macrotest = "1.0"
