[package]
name = "struct_io"
version = "0.1.0"
edition = "2024"
authors = ["nbhdai"]

[workspace]
members = []

[dependencies.http_client]
path = "../../capabilities/http_client/module"
optional = true

[dependencies.pyroduct]
path = "../../lib/pyroduct"

[lib]
crate-type = ["cdylib"]
required-features = []
