[package]
name = "http_client"
version = "0.1.0"
edition = "2024"
authors = ["nbhdai"]

[dependencies.pyroduct]
path = "../../lib/pyroduct"

[dependencies.reqwest]
version = "0.13.1"
features = ["json"]
optional = true

[features]
capability = ["dep:reqwest"]
default = []
module = []

[lib]
crate-type = ["cdylib"]
required-features = []
