#![doc = r" Automatically generated by pyroduct. DO NOT EDIT."]
#![allow(unused_imports, dead_code, unused_variables, nonstandard_style)]
use pyroduct;
#[derive(
    :: pyroduct :: rkyv :: Archive,
    :: pyroduct :: rkyv :: Serialize,
    :: pyroduct :: rkyv :: Deserialize,
)]
# [rkyv (crate = :: pyroduct :: rkyv)]
pub struct RagClient;
impl RagClient {
    pub fn register(self) -> Result<::pyroduct::module_capability::Client<Self>, String> {
        let __config_buf = ::pyroduct::rkyv::to_bytes::<::pyroduct::rkyv::rancor::Error>(&self)
            .expect("Failed to serialize config");
        let ffi_result =
            ::pyroduct::module_capability::access::call_from_wasm::<(), Result<(), String>, _>(
                "__rag_server__new_client",
                Some(&__config_buf),
                None,
                |client_state_ptr: *const u8,
                 client_state_len: usize,
                 input_ptr: *const u8,
                 input_len: usize| {
                    unsafe {
                        wasm::__rag_server__new_client__wasm(
                            client_state_ptr,
                            client_state_len,
                            input_ptr,
                            input_len,
                        )
                    }
                },
            );
        match ffi_result {
            Ok(_) => Ok(::pyroduct::module_capability::Client::new(
                self,
                __config_buf,
            )),
            Err(e) => Err(e.into()),
        }
    }
}
pub trait RagClientMethods {
    fn search(&self, query: String) -> Result<Vec<SearchResult>, String>;
    fn search_with_k(&self, query: String, k: usize) -> Result<Vec<SearchResult>, String>;
}
impl RagClientMethods for ::pyroduct::module_capability::Client<RagClient> {
    fn search(&self, query: String) -> Result<Vec<SearchResult>, String> {
        ::pyroduct::module_capability::access::call_from_wasm::<
            String,
            Result<Vec<SearchResult>, String>,
            _,
        >(
            "__rag_server__search",
            Some(self.buffer()),
            Some(&query),
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__rag_server__search__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
    fn search_with_k(&self, query: String, k: usize) -> Result<Vec<SearchResult>, String> {
        #[derive(
            :: pyroduct :: rkyv :: Archive,
            :: pyroduct :: rkyv :: Deserialize,
            :: pyroduct :: rkyv :: Serialize,
        )]
        # [rkyv (crate = :: pyroduct :: rkyv)]
        struct __RagServer__SearchWithK__Input {
            pub query: String,
            pub k: usize,
        }
        ::pyroduct::module_capability::access::call_from_wasm::<
            __RagServer__SearchWithK__Input,
            Result<Vec<SearchResult>, String>,
            _,
        >(
            "__rag_server__search_with_k",
            Some(self.buffer()),
            Some(&__RagServer__SearchWithK__Input { query, k }),
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__rag_server__search_with_k__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
}
mod wasm {
    use super::*;
    #[link(wasm_import_module = "env")]
    unsafe extern "C" {
        pub fn __rag_server__new_client__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __rag_server__search__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __rag_server__search_with_k__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
    }
}
#[derive(
    :: pyroduct :: rkyv :: Archive,
    :: pyroduct :: rkyv :: Serialize,
    :: pyroduct :: rkyv :: Deserialize,
)]
# [rkyv (crate = :: pyroduct :: rkyv)]
pub struct SearchResult {
    pub id: String,
    pub content: String,
    pub score: f32,
}
