[package]
name = "pyro-spec"
version = { workspace = true }
description = "Schema and specs for functions and rows in pyroduct"
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[features]
arrow = ["dep:arrow-schema", "dep:tracing"]

[dependencies]
serde.workspace = true
thiserror.workspace = true
arrow-schema = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
