[module]
name = "cap_config"
version = "0.1.0"
author = "nbhdai"

[pyroduct]
path = "../../lib/pyroduct/"

[capabilities]
config = { package = "config", author = "nbhdai", version = "0.1.0", configuration = { type = "capabilityconfig", classes = { transform = { uppercase = true, suffix = "!!!" } } } }

[dependencies]
