[package]
name = "pyroduct"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
capability = [
    "dep:async-ffi",
    "dep:tokio",
    "dep:pin-project",
    "dep:libloading",
    "dep:futures",
]
host = [
    "dep:tokio",
    "dep:async-ffi",
    "dep:futures",
    "dep:wasmtime",
    "dep:arrow",
    "dep:parquet",
    "dep:libloading",
    "dep:pin-project",
    "dep:object",
    "spec/arrow",
]
module = []

[dependencies]
artifacts.workspace = true
spec.workspace = true
pyro-derive.workspace = true
rkyv.workspace = true
tracing.workspace = true

# Errors
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

# Value dependencies
half.workspace = true
paste = "1.0.15"
chrono = { version = "0.4.43", default-features = false, features = ["alloc"] }


tracing-subscriber.workspace = true
dashmap = "6.1.0"

# Async (not for wasm)
tokio = { workspace = true, optional = true }
async-ffi = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
wasmtime = { workspace = true, optional = true }

# Arrow
arrow = { workspace = true, optional = true }
parquet = { workspace = true, optional = true }

pin-project = { workspace = true, optional = true }
libloading = { workspace = true, optional = true }
object = { workspace = true, optional = true }
indexmap = { version = "2.13.0", features = ["serde"] }

[dev-dependencies]
trybuild.workspace = true
macrotest = "1.0"
tracing-test.workspace = true

[[test]]
name = "derive_tests"
required-features = ["module", "capability"] 

[[test]]
name = "logs"
required-features = ["host"]

[[test]]
name = "tokio_safety"
required-features = ["host"]

[[test]]
name = "integration_state"
required-features = ["host"]

[[test]]
name = "integration_config"
required-features = ["host"]

[[test]]
name = "ffi_safety"
required-features = ["host", "capability"]
