[package]
name = "pyroduct"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
capability = []
host = []
module = []

[dependencies]

arrow.workspace = true
arrow-scalars = { path = "../arrow-scalars", default-features = false, features = [] }
arrow-derive = { path = "../arrow-derive", default-features = false, features = ["pyroduct"] }

module-derive = { path = "../module-derive" }
rkyv.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
capability-derive = { path = "../capability-derive" }
wasmtime.workspace = true
pin-project.workspace = true
async-ffi.workspace = true
libloading.workspace = true
tokio.workspace = true
futures.workspace = true

[dev-dependencies]
tracing-test = "0.2.5"
trybuild = "1.0"
macrotest = "1.0"
tempfile = "3.24.0"
