[package]
name = "pyroduct"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
# capability = []
ffi_host = []
module = []
wasm_host = []
wasm = []

[dependencies]
pyro-derive.workspace = true
rkyv.workspace = true
tracing.workspace = true

# Errors
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

# Value dependencies
half.workspace = true
paste = "1.0.15"
chrono = { version = "0.4.43", default-features = false, features = ["alloc"] }


tracing-subscriber.workspace = true
dashmap = "6.1.0"

# Async (not for wasm)
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio.workspace = true
async-ffi.workspace = true
futures.workspace = true
wasmtime.workspace = true

# Arrow
arrow.workspace = true
parquet.workspace = true

pin-project.workspace = true
libloading.workspace = true
object.workspace = true

[dev-dependencies]
trybuild.workspace = true
macrotest = "1.0"

tracing-test.workspace = true

[[test]]
name = "derive_tests"
# Specify the exact features required to run the macro compile tests
required-features = ["module", "ffi_host"] 

[[test]]
name = "integration_state"
required-features = ["ffi_host"]

[[test]]
name = "integration_config"
required-features = ["ffi_host"]