libraries:
  transform: ../../capabilities/config/

modules:
  prefix:
    path: ../../modules/cap_config/
    capabilities:
      transform:
        uppercase: true
        suffix: "!!!"

pipeline:
  - prefix