[module]
name = "chat"
version = "0.1.0"
author = "nbhdai"


[pyroduct]
path = "../../lib/pyroduct/"

[capabilities]
llm = { package = "llm", author = "nbhdai", version = "0.1.0", configuration = { type = "capabilityconfig", classes = { llmserver = { base_url = "http://localhost:11434", system_prompt = "", permitted_models = ["gemma3:270m"] } } } }

[dependencies]
