[module]
name = "chat"
version = "0.1.0"
author = "nbhdai"


[pyroduct]
path = "../../lib/pyroduct"

[capabilities]
ollama = { package = "ollama", author = "nbhdai", version = "0.1.0" }

[dependencies]
