[package]
name = "arrow-scalars"
version = "0.3.10"
edition = "2021"

[features]
default = ["macros"]
macros = ["dep:arrow-derive"]

[dependencies]
arrow-derive = { workspace = true, optional = true }
arrow-schema.workspace = true

thiserror.workspace = true
serde.workspace = true
half.workspace = true
rkyv.workspace = true

paste = "1.0.15"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
arrow.workspace = true 

[dev-dependencies]
tempfile.workspace = true
tracing-test.workspace = true
trybuild.workspace = true
macrotest.workspace = true
serde_json.workspace = true