//! This crate provides proc macros to generate FFI boilerplate for capabilities.
use syn::parse_file;
use crate::{capability::CapabilityImpl, client::CapInterfaceItem, config::CapConfig};

pub mod capability;
pub mod client;
pub mod config;
pub mod ffi;
pub mod lifecycle;
pub mod methods;
pub mod paths;
pub mod spec;
pub mod utils;

/// For generating the interface lib.rs (module-side code)
pub fn generate_interface(
    content: &str,
    cap_name: &str,
    cap_version: &str,
) -> syn::Result<(syn::File, anyhow::Result<String>, Option<anyhow::Result<String>>)> {
    let file = parse_file(content)?;

    let failure_error = syn::Error::new_spanned(&file, "No capability found");

    let mut generated_code = quote::quote! {
        //! Automatically generated by pyroduct. DO NOT EDIT.
        #![allow(unused_imports, dead_code, unused_variables, nonstandard_style)]
        use pyroduct;
    };

    let mut capability = None;
    let mut interfaces = Vec::new();
    let mut config = None;
    for item in file.items {
        match item {
            syn::Item::Impl(item_impl) => {
                if has_attr(&item_impl.attrs, "capability") {
                    let cap = CapabilityImpl::new(item_impl, true, cap_name, cap_version)?;
                    generated_code.extend(cap.expand_module());
                    capability = Some(cap);
                }
            }
            syn::Item::Struct(item_struct) => {
                if has_attr(&item_struct.attrs, "interface_item") {
                    let interface = CapInterfaceItem::new(item_struct, false)?;
                    generated_code.extend(interface.expand());
                    interfaces.push(interface);
                } else if has_attr(&item_struct.attrs, "config") {
                    let found_config = CapConfig::new(item_struct, config::DocRec::StructDoc)?;
                    config = Some(found_config);
                }
            }
            _ => {}
        }
    }
    let mut spec_builder = if let Some(cap) = capability {
        spec::SpecBuilder::new(&cap)
    } else {
        return Err(failure_error);
    };
    for interface in interfaces {
        spec_builder.append(&interface);
    }
    let spec = spec_builder.build();

    let config = if let Some(cap) = config {
        Some(spec::ConfigSpecBuilder::build(&cap))
    } else {
        None
    };
    let code: syn::File = syn::parse2(generated_code)?;
    Ok((code, spec, config))
}

/// For generating the capability lib.rs (host-side code)
pub fn generate_capability(
    content: &str,
    cap_name: &str,
    cap_version: &str,
) -> syn::Result<syn::File> {
    let file = parse_file(content)?;

    let mut generated_code = quote::quote! {
        //! Automatically generated by pyroduct. DO NOT EDIT.
        #![allow(unused_imports, dead_code, unused_variables, nonstandard_style)]
        use pyroduct;
    };

    for item in file.items {
        match item {
            syn::Item::Impl(item_impl) => {
                if has_attr(&item_impl.attrs, "capability") {
                    let cap = CapabilityImpl::new(item_impl, true, cap_name, cap_version)?;
                    generated_code.extend(cap.expand_capability());
                }
            }
            syn::Item::Struct(item_struct) => {
                if has_attr(&item_struct.attrs, "interface_item") {
                    let interface = CapInterfaceItem::new(item_struct, false)?;
                    generated_code.extend(interface.expand());
                } else if has_attr(&item_struct.attrs, "config") {
                    let found_config = CapConfig::new(item_struct, config::DocRec::StructDoc)?;
                    generated_code.extend(found_config.expand());
                }
            }
            _ => {}
        }
    }

    let code: syn::File = syn::parse2(generated_code)?;
    Ok(code)
}

fn has_attr(attrs: &[syn::Attribute], name: &str) -> bool {
    attrs.iter().any(|a| {
        if a.path().is_ident(name) {
            return true;
        }
        if a.path().segments.len() == 2
            && a.path().segments[0].ident == "pyroduct"
            && a.path().segments[1].ident == name
        {
            return true;
        }
        false
    })
}

#[cfg(test)]
pub mod fmt {
    use proc_macro2::TokenStream;

    pub fn format_tokens(tokens: &TokenStream) -> String {
        match syn::parse_file(&tokens.to_string()) {
            Ok(file) => prettyplease::unparse(&file),
            Err(err) => {
                println!("Parsing Error {err:?}");
                tokens.to_string()
            }
        }
    }

    pub fn assert_code_eq_token(tokens: &TokenStream, expected: &TokenStream) {
        let actual_file: syn::File = syn::parse2(tokens.clone())
            .expect("Generated tokens are not valid Rust code (syn::File)");
        let expected_file: syn::File = syn::parse2(expected.clone())
            .expect("Expected string is not valid Rust code (syn::File)");
        let actual_str = prettyplease::unparse(&actual_file);
        let expected_str = prettyplease::unparse(&expected_file);
        if actual_str != expected_str {
            panic!(
                "Code mismatch!\n\nEXPECTED:\n{}\n\nACTUAL:\n{}\n",
                expected_str, actual_str
            );
        }
    }
}
