//! Capability Derive Macros
//!
//! This crate provides proc macros to generate FFI boilerplate for capabilities.
//!
//! # Patterns Supported
//!
//! 1. **Stateless functions** - `#[capability_function]` on standalone functions
//! 2. **Host state only** - `#[capability]` trait + `#[capability_server]` struct
//! 3. **Client state only** - `#[capability_client]` struct + `#[capability(stateless)]` trait
//! 4. **Both states** - `#[capability_client]` struct + `#[capability]` trait + `#[capability_server]` struct

use anyhow::Context;
use syn::parse_file;

use crate::{capability::CapabilityImpl, client::CapClient, config::CapConfig};

pub mod config;
pub mod client;
pub mod ffi;
pub mod paths;
pub mod utils;
pub mod methods;
pub mod lifecycle;
pub mod capability;

/// For generating the client lib.rs
pub fn generate_client(content: &String) -> anyhow::Result<String> {
    let file = parse_file(&content)
            .context("Failed to parse capability source file")?;

    let mut generated_code = quote::quote! {
        //! Automatically generated by pyroduct. DO NOT EDIT.
        #![allow(unused_imports, dead_code, unused_variables)]
        use pyroduct;
    };

    for item in file.items {
        match item {
            syn::Item::Impl(item_impl) => {
                if has_attr(&item_impl.attrs, "capability") {
                    let cap = CapabilityImpl::new(item_impl)
                            .map_err(|e| anyhow::anyhow!("{}", e))?;
                    generated_code.extend(cap.expand_module()); 
                }
            }
            syn::Item::Struct(item_struct) => {
                if has_attr(&item_struct.attrs, "config") {
                    let config = CapConfig::new(item_struct)
                            .map_err(|e| anyhow::anyhow!("{}", e))?;
                    generated_code.extend(config.expand());
                } else if has_attr(&item_struct.attrs, "client") {
                    let client = CapClient::new(item_struct)
                            .map_err(|e| anyhow::anyhow!("{}", e))?;
                    generated_code.extend(client.expand());
                }
            }
            _ => {}
        }
    }

    Ok(generated_code.to_string())
}


fn has_attr(attrs: &[syn::Attribute], name: &str) -> bool {
    attrs.iter().any(|a| {
        if a.path().is_ident(name) { return true; }
        if a.path().segments.len() == 2 
           && a.path().segments[0].ident == "pyroduct" 
           && a.path().segments[1].ident == name { return true; }
        false
    })
}

#[cfg(test)]
pub mod fmt {
    use proc_macro2::TokenStream;

    pub fn format_tokens(tokens: &TokenStream) -> String {
        match syn::parse_file(&tokens.to_string()) {
            Ok(file) => prettyplease::unparse(&file),
            Err(err) => {
                println!("Parsing Error {err:?}");
                tokens.to_string()
            }
        }
    }

    pub fn assert_code_eq_token(tokens: &TokenStream, expected: &TokenStream) {
        let actual_file: syn::File = syn::parse2(tokens.clone())
            .expect("Generated tokens are not valid Rust code (syn::File)");
        let expected_file: syn::File = syn::parse2(expected.clone())
            .expect("Expected string is not valid Rust code (syn::File)");
        let actual_str = prettyplease::unparse(&actual_file);
        let expected_str = prettyplease::unparse(&expected_file);
        if actual_str != expected_str {
            panic!(
                "Code mismatch!\n\nEXPECTED:\n{}\n\nACTUAL:\n{}\n",
                expected_str, actual_str
            );
        }
    }
}