[package]
name = "pyro-spec"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
arrow = ["dep:arrow-schema", "dep:tracing"]

[dependencies]
serde.workspace = true
thiserror.workspace = true
arrow-schema = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
