[package]
name = "pyro-derive"
version = { workspace = true }
description = "Derive macros for pyroduct"
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
pyro-macro.workspace = true
syn.workspace = true
quote.workspace = true
