[capability]
author = "nbhdai"
name = "httpc"
version = "0.1.0"

[pyroduct]
version = "0.1.0"
  
[dependencies.host]
reqwest = { version = "0.13.1", features = [ "json" ] }
  
[dependencies.module]

[dependencies.shared]
