//! Automatically generated by pyroduct. DO NOT EDIT.
#![allow(unused_imports, dead_code, unused_variables, nonstandard_style)]
use pyroduct;
impl ::pyroduct::value::TypeableRow for CpuClient {
    fn schema() -> ::pyroduct::value::PyroSchema<'static> {
        ::pyroduct::value::PyroSchema {
            fields: ::std::borrow::Cow::Owned(vec![]),
            documentation: None,
        }
    }
}
impl ::pyroduct::value::TypeableRow for CpuClientRef<'_> {
    fn schema() -> ::pyroduct::value::PyroSchema<'static> {
        ::pyroduct::value::PyroSchema {
            fields: ::std::borrow::Cow::Owned(vec![]),
            documentation: None,
        }
    }
}
#[derive(
    ::pyroduct::rkyv_8::rkyv::Archive,
    ::pyroduct::rkyv_8::rkyv::Serialize,
    ::pyroduct::rkyv_8::rkyv::Deserialize
)]
#[rkyv(crate = ::pyroduct::rkyv_8::rkyv)]
pub struct CpuClient;
impl ::pyroduct::format::UserHeaderValues for CpuClient {
    const VERSION: u8 = 0;
}
impl ::pyroduct::Bridgeable for CpuClient {
    type Format = ::pyroduct::rkyv_8::Rkyv<CpuClient>;
}
#[derive()]
pub struct CpuClientRef<'a> {
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl ::pyroduct::DeepRef for CpuClient {
    type Ref<'a> = CpuClientRef<'a>;
    fn as_deep_ref(&self) -> Self::Ref<'_> {
        CpuClientRef {
            _phantom: std::marker::PhantomData,
        }
    }
}
impl ::pyroduct::DeepRef for ArchivedCpuClient {
    type Ref<'a> = CpuClientRef<'a>;
    fn as_deep_ref(&self) -> Self::Ref<'_> {
        CpuClientRef {
            _phantom: std::marker::PhantomData,
        }
    }
}
impl<'a> std::convert::TryFrom<::pyroduct::PyroRow<'a>> for CpuClient {
    type Error = ::pyroduct::PyroRow<'a>;
    fn try_from(row: ::pyroduct::PyroRow<'a>) -> Result<Self, Self::Error> {
        let result = (|| -> Result<Self, &'static str> { Ok(Self {}) })();
        result.map_err(|_| row)
    }
}
impl<'a> std::convert::TryFrom<&::pyroduct::PyroRow<'a>> for CpuClient {
    type Error = &'static str;
    fn try_from(row: &::pyroduct::PyroRow<'a>) -> Result<Self, Self::Error> {
        Ok(Self {})
    }
}
impl<'a> std::convert::TryFrom<::pyroduct::PyroValue<'a>> for CpuClient {
    type Error = ::pyroduct::PyroValue<'a>;
    fn try_from(value: ::pyroduct::PyroValue<'a>) -> Result<Self, Self::Error> {
        match value {
            ::pyroduct::PyroValue::Group(r) => {
                match <Self as std::convert::TryFrom<
                    ::pyroduct::PyroRow<'a>,
                >>::try_from(r) {
                    Ok(s) => Ok(s),
                    Err(r) => Err(::pyroduct::PyroValue::Group(r)),
                }
            }
            v => Err(v),
        }
    }
}
impl<'a> std::convert::TryFrom<&::pyroduct::PyroValue<'a>> for CpuClient {
    type Error = &'static str;
    fn try_from(value: &::pyroduct::PyroValue<'a>) -> Result<Self, Self::Error> {
        match value {
            ::pyroduct::PyroValue::Group(r) => {
                <Self as std::convert::TryFrom<&::pyroduct::PyroRow<'a>>>::try_from(r)
            }
            _ => Err("Expected Group"),
        }
    }
}
impl<'a> std::convert::TryFrom<::pyroduct::PyroRow<'a>> for CpuClientRef<'a> {
    type Error = ::pyroduct::PyroRow<'a>;
    fn try_from(row: ::pyroduct::PyroRow<'a>) -> Result<Self, Self::Error> {
        let result = (|| -> Result<Self, &'static str> {
            Ok(Self {
                _phantom: std::marker::PhantomData,
            })
        })();
        result.map_err(|_| row)
    }
}
impl<'a> std::convert::TryFrom<&::pyroduct::PyroRow<'a>> for CpuClientRef<'a> {
    type Error = &'static str;
    fn try_from(row: &::pyroduct::PyroRow<'a>) -> Result<Self, Self::Error> {
        Ok(Self {
            _phantom: std::marker::PhantomData,
        })
    }
}
impl<'a> std::convert::TryFrom<::pyroduct::PyroValue<'a>> for CpuClientRef<'a> {
    type Error = ::pyroduct::PyroValue<'a>;
    fn try_from(value: ::pyroduct::PyroValue<'a>) -> Result<Self, Self::Error> {
        match value {
            ::pyroduct::PyroValue::Group(r) => {
                match <Self as std::convert::TryFrom<
                    ::pyroduct::PyroRow<'a>,
                >>::try_from(r) {
                    Ok(s) => Ok(s),
                    Err(r) => Err(::pyroduct::PyroValue::Group(r)),
                }
            }
            v => Err(v),
        }
    }
}
impl<'a> std::convert::TryFrom<&::pyroduct::PyroValue<'a>> for CpuClientRef<'a> {
    type Error = &'static str;
    fn try_from(value: &::pyroduct::PyroValue<'a>) -> Result<Self, Self::Error> {
        match value {
            ::pyroduct::PyroValue::Group(r) => {
                <Self as std::convert::TryFrom<&::pyroduct::PyroRow<'a>>>::try_from(r)
            }
            _ => Err("Expected Group"),
        }
    }
}
impl ::pyroduct::ToRow for CpuClient {
    fn to_row(&self) -> ::pyroduct::PyroRow<'_> {
        ::pyroduct::PyroRow::new()
    }
}
impl CpuClient {
    pub fn register(self) -> ::pyroduct::wasm::Client<Self> {
        ::pyroduct::wasm::Client::<
            Self,
        >::__register(self, |ptr| unsafe { wasm::p__cpu_server__register__wasm(ptr) })
    }
}
pub trait CpuClientMethods {
    /// Returns the number of vcpus the host machine has
    fn get_cpu_count(&self) -> u32;
}
impl CpuClientMethods for ::pyroduct::wasm::Client<CpuClient> {
    /// Returns the number of vcpus the host machine has
    fn get_cpu_count(&self) -> u32 {
        self.__call_from_wasm::<
                (),
                u32,
                _,
            >(
            None,
            |client_state_ptr: *const u8, input_ptr: *const u8| {
                unsafe {
                    wasm::p__cpu_server__get_cpu_count__wasm(client_state_ptr, input_ptr)
                }
            },
        )
    }
}
mod wasm {
    use super::*;
    #[link(wasm_import_module = "cpu_client")]
    unsafe extern "C" {
        pub fn p__cpu_server__register__wasm(ptr: *const u8) -> *mut u8;
        pub fn p__cpu_server__get_cpu_count__wasm(
            cs_ptr: *const u8,
            in_ptr: *const u8,
        ) -> *mut u8;
    }
}
