#![doc = r" Automatically generated by pyroduct. DO NOT EDIT."]
#![allow(unused_imports, dead_code, unused_variables)]
use pyroduct;
#[derive(
    :: pyroduct :: rkyv :: Archive,
    :: pyroduct :: rkyv :: Serialize,
    :: pyroduct :: rkyv :: Deserialize,
)]
# [rkyv (crate = :: pyroduct :: rkyv)]
pub struct CpuClient;
impl CpuClient {
    pub fn register(self) -> ::pyroduct::module_capability::Client<Self> {
        let __config_buf = ::pyroduct::rkyv::to_bytes::<::pyroduct::rkyv::rancor::Error>(&self)
            .expect("Failed to serialize config");
        ::pyroduct::module_capability::access::call_from_wasm::<(), (), _>(
            "__cpu_server__new_client",
            Some(&__config_buf),
            None,
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__cpu_server__new_client__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        );
        ::pyroduct::module_capability::Client::new(self, __config_buf)
    }
}
pub trait CpuClientMethods {
    fn get_cpu_count(&self) -> u32;
}
impl CpuClientMethods for ::pyroduct::module_capability::Client<CpuClient> {
    fn get_cpu_count(&self) -> u32 {
        ::pyroduct::module_capability::access::call_from_wasm::<(), u32, _>(
            "__cpu_server__get_cpu_count",
            Some(self.buffer()),
            None,
            |client_state_ptr: *const u8,
             client_state_len: usize,
             input_ptr: *const u8,
             input_len: usize| {
                unsafe {
                    wasm::__cpu_server__get_cpu_count__wasm(
                        client_state_ptr,
                        client_state_len,
                        input_ptr,
                        input_len,
                    )
                }
            },
        )
    }
}
pub mod wasm {
    use super::*;
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "env")]
    unsafe extern "C" {
        pub fn __cpu_server__new_client__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
        pub fn __cpu_server__get_cpu_count__wasm(
            cs_ptr: *const u8,
            cs_len: usize,
            in_ptr: *const u8,
            in_len: usize,
        ) -> *const u8;
    }
}
