name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Build & Test
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        run: |
          git config --global --add safe.directory "$PWD"
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} || true
          git fetch --depth=1 origin ${{ github.sha }}
          git checkout -f FETCH_HEAD

      - name: Build & Test in Nix DevShell
        run: |
          nix develop --command bash -c "
            set -e
            export RUST_BACKTRACE=1
            prepare-pyro
            test-rust
          "
